/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programas;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JFrame;

/**
 *
 * @author crist
 */
public class ArbolPane extends javax.swing.JPanel {

    /**
     * Creates new form ArbolPane
     */
    
    public int radio = 20;
    public int mitadRadio = radio/2;
    
    public ArbolPane() {
        initComponents();
    }

    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        
        Graphics2D g2d = (Graphics2D)g;
    
       // fillOval(x,y, ancho, alto)
       g2d.setColor(Color.red);
       g2d.drawLine(getWidth()/2, 10,getWidth()/2, 40);
              
       g2d.setColor(Color.black);
       g2d.setStroke(new BasicStroke(2));
       g2d.fillOval(getWidth()/2-15, 10, 30, 30); 
    
        
       g2d.setStroke(new BasicStroke(2));
       g2d.setColor(Color.BLACK);
       // drawLine(Px1,Py1, Px2, Py2)
       // Dibujar linea de Punto(x1,y1) a Punto(x2,y2)
       g2d.drawLine(getWidth()/2,50, (getWidth()/2)-30, 70);
        
       g2d.drawLine(getWidth()/2,50, (getWidth()/2)+30, 70);
        
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public static void main(String[] args){
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400,400);
        frame.add(new ArbolPane());
        frame.setVisible(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
